"""InvitationsAccounts

Revision ID: 07c1deb111b3
Revises: 7cb74aee4764
Create Date: 2023-10-05 23:34:09.913870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c1deb111b3'
down_revision = '7cb74aee4764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("invitation_account", 'account', ['recipient_id'], ['account_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_constraint("invitation_account", type_='foreignkey')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
