"""FuckingRename

Revision ID: 10156f6142d2
Revises: 536756b4a138
Create Date: 2023-09-10 13:32:11.431831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10156f6142d2'
down_revision = '536756b4a138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        op.execute('''ALTER TABLE account RENAME COLUMN id TO account_id''')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        op.execute('''ALTER TABLE account RENAME COLUMN account_id TO id''')

    # ### end Alembic commands ###
