"""emails

Revision ID: 1d1b3cc7fd46
Revises: 61862ce29496
Create Date: 2024-04-13 22:06:21.142702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1b3cc7fd46'
down_revision = '61862ce29496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed_to_emails', sa.Boolean(), nullable=False, server_default=str(1)))

    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=False, server_default=str(1)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_column('notifications_enabled')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('subscribed_to_emails')

    # ### end Alembic commands ###
