"""Chore

Revision ID: 23c6bd0f19db
Revises: ff6bcf348e67
Create Date: 2023-09-13 23:21:03.368181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c6bd0f19db'
down_revision = 'ff6bcf348e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore',
    sa.Column('chore_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('repeat_days', sa.Integer(), nullable=True),
    sa.Column('repeat_day_of_week', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('chore_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chore')
    # ### end Alembic commands ###
