"""RepeatType

Revision ID: 23e5445a3252
Revises: 23c6bd0f19db
Create Date: 2023-09-16 21:53:08.348893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e5445a3252'
down_revision = '23c6bd0f19db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_type', sa.Integer(), nullable=False, server_default=str(0)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_column('repeat_type')

    # ### end Alembic commands ###
