"""one time due date

Revision ID: 36c765c4fd81
Revises: 83149d902f8d
Create Date: 2023-12-09 21:01:14.305703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c765c4fd81'
down_revision = '83149d902f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('one_time_due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_column('archived')
        batch_op.drop_column('one_time_due_date')

    # ### end Alembic commands ###
