"""ListChore

Revision ID: 454e808f5e59
Revises: 68fe1150bad6
Create Date: 2023-09-25 23:11:41.648455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454e808f5e59'
down_revision = '68fe1150bad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("list_id", 'list', ['list_id'], ['list_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('list_id')

    # ### end Alembic commands ###
