"""LastLogin

Revision ID: 536756b4a138
Revises: 18ea3ca8170c
Create Date: 2023-09-09 20:16:33.207295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536756b4a138'
down_revision = '18ea3ca8170c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
