"""AddCapitalizeNameBoolean

Revision ID: 61862ce29496
Revises: 9f645f8281c3
Create Date: 2024-03-24 20:27:54.640061

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '61862ce29496'
down_revision = '9f645f8281c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capitalize_name', sa.Boolean(), nullable=False, server_default=str(0)))

    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.alter_column(
            'accepted',
            existing_type=sa.BOOLEAN(),
            nullable=False,
            server_default=str(0)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.alter_column('accepted',
                              existing_type=sa.BOOLEAN(),
                              nullable=True)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('capitalize_name')

    # ### end Alembic commands ###
