"""due_date

Revision ID: 68fe1150bad6
Revises: 7461b54f63ab
Create Date: 2023-09-18 22:37:31.152317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fe1150bad6'
down_revision = '7461b54f63ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_log', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
