"""request_ip

Revision ID: 72b80fb37c75
Revises: 1d1b3cc7fd46
Create Date: 2024-04-16 19:41:09.662893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b80fb37c75'
down_revision = '1d1b3cc7fd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_request_ip', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('last_request_ip')

    # ### end Alembic commands ###
