"""ChoreLogChoreId

Revision ID: 7461b54f63ab
Revises: 8d13ed1918a6
Create Date: 2023-09-18 21:24:42.234536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7461b54f63ab'
down_revision = '8d13ed1918a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('chore_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('chore_id', 'chore', ['chore_id'], ['chore_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chore_id')
        batch_op.drop_column('completed_date')

    # ### end Alembic commands ###
