"""Invitations

Revision ID: 7cb74aee4764
Revises: 454e808f5e59
Create Date: 2023-10-05 23:08:22.219133

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7cb74aee4764'
down_revision = '454e808f5e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation',
                    sa.Column('invitation_id', sa.Integer(), nullable=False),
                    sa.Column('accepted', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('invitation_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation')
    # ### end Alembic commands ###
