"""chore month

Revision ID: 83149d902f8d
Revises: a0319e06b22d
Create Date: 2023-12-08 23:45:51.520624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83149d902f8d'
down_revision = 'a0319e06b22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_day_of_month', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_column('repeat_day_of_month')

    # ### end Alembic commands ###
