"""StartChoreLog

Revision ID: 8d13ed1918a6
Revises: 23e5445a3252
Create Date: 2023-09-18 21:00:26.523702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d13ed1918a6'
down_revision = '23e5445a3252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore_log',
    sa.Column('chore_log_id', sa.Integer(), nullable=False),
    sa.Column('completed_by_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('chore_log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chore_log')
    # ### end Alembic commands ###
