"""ListOwner

Revision ID: a0319e06b22d
Revises: 07c1deb111b3
Create Date: 2023-11-25 16:27:43.356515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0319e06b22d'
down_revision = '07c1deb111b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("list_owner_id_fk", 'account', ['owner_id'], ['account_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_constraint("list_owner_id_fk", type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
